name: Keep Render Alive

on:
  schedule:
    - cron: '*/3 * * * *'  # Ping mỗi 3 phút

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://chillnet-backend.onrender.com/health
